project:
  type: website
  output-dir: build/site
  render:
    - index.md
    - "notes/personal/**/*.md"

format:
  html:
    format-links: false

website:
  title: Project Polaris Academy
  page-navigation: true
  navbar:
    left:
      - text: Jon Leithe
        href: https://www.jonleithe.no/
  sidebar:
    style: docked
    search: true
