project:
  type: website
  output-dir: build/site
  render:
    - index.md
    - "notes/personal/**/*.md"

format:
  html:
    format-links: false

website:
  title: Project Polaris Academy
  page-navigation: true
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.md
        text: Home
      - auto: "notes/personal/**"
