#!/usr/bin/env python3
"""Generate the ordered chapter profile for the personal-notes book."""

from __future__ import annotations

import argparse
import json
import os
import re
import tempfile
from pathlib import Path


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a Quarto book profile from Markdown notes."
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path.cwd(),
        help="Repository root (default: current directory).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("_quarto-auto-book.yml"),
        help="Generated profile path, relative to the project root by default.",
    )
    return parser.parse_args()


def front_matter_course(note_path: Path) -> str:
    """Return a note's scalar course value, or an empty string if absent."""
    lines = note_path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        return ""

    for line in lines[1:]:
        if line.strip() in {"---", "..."}:
            break

        match = re.match(r"^course\s*:\s*(.*?)\s*$", line)
        if not match:
            continue

        value = match.group(1)
        if len(value) >= 2 and value[0] == value[-1] == "'":
            return value[1:-1].replace("''", "'")
        if len(value) >= 2 and value[0] == value[-1] == '"':
            return json.loads(value)
        return value

    return ""


def render_profile(project_root: Path) -> tuple[str, int]:
    notes_directory = project_root / "notes" / "personal"
    if not notes_directory.is_dir():
        raise FileNotFoundError(
            f"personal notes directory not found: {notes_directory}"
        )

    note_paths = sorted(
        (
            path
            for path in notes_directory.rglob("*.md")
            if path.is_file()
        ),
        key=lambda path: path.relative_to(project_root).as_posix(),
    )
    chapters = [
        path.relative_to(project_root).as_posix()
        for path in note_paths
    ]
    courses = [
        front_matter_course(path)
        for path in note_paths
    ]

    lines = [
        "# Generated by scripts/generate-book-profile.py; do not edit.",
        "book:",
        "  chapters:",
        f"    - {json.dumps('index.md')}",
    ]
    lines.extend(f"    - {json.dumps(chapter)}" for chapter in chapters)
    lines.extend(
        [
            "metadata:",
            "  academy-chapter-courses:",
            f"    {json.dumps('1')}: {json.dumps('')}",
        ]
    )
    lines.extend(
        f"    {json.dumps(str(index))}: {json.dumps(course)}"
        for index, course in enumerate(courses, start=2)
    )
    return "\n".join(lines) + "\n", len(chapters)


def write_if_changed(output_path: Path, content: str) -> None:
    if output_path.is_file() and output_path.read_text(encoding="utf-8") == content:
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        dir=output_path.parent,
        prefix=f".{output_path.name}.",
        delete=False,
    ) as temporary_file:
        temporary_file.write(content)
        temporary_path = Path(temporary_file.name)

    os.replace(temporary_path, output_path)


def main() -> None:
    arguments = parse_arguments()
    project_root = arguments.project_root.resolve()
    output_path = arguments.output
    if not output_path.is_absolute():
        output_path = project_root / output_path

    content, chapter_count = render_profile(project_root)
    write_if_changed(output_path, content)
    print(f"Generated {output_path.name} with {chapter_count} note chapters")


if __name__ == "__main__":
    main()
