#!/usr/bin/env python3
"""Generate ordered Quarto profiles for the Academy book and site."""

from __future__ import annotations

import argparse
import json
import os
import re
import tempfile
from pathlib import Path


THEOREMS_NOTE = Path("notes/personal/00-theorems.md")
KHAN_ACADEMY_NOTES = (
    Path("notes/linear-algebra/courses/khan-academy/01-vectors-and-spaces.md"),
    Path("notes/linear-algebra/courses/khan-academy/02-linear-combinations-and-span.md"),
    Path(
        "notes/linear-algebra/courses/khan-academy/"
        "03-linear-dependence-and-independence.md"
    ),
    Path(
        "notes/linear-algebra/courses/khan-academy/"
        "04-subspaces-and-the-basis-for-a-subspace.md"
    ),
    Path(
        "notes/linear-algebra/courses/khan-academy/"
        "05-vector-dot-and-cross-products.md"
    ),
)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a Quarto book profile from Markdown notes."
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path.cwd(),
        help="Repository root (default: current directory).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("_quarto-auto-book.yml"),
        help="Generated book profile path, relative to the project root by default.",
    )
    parser.add_argument(
        "--site-output",
        type=Path,
        default=Path("_quarto-auto-site.yml"),
        help="Generated site profile path, relative to the project root by default.",
    )
    return parser.parse_args()


def front_matter_course(note_path: Path) -> str:
    """Return a note's scalar course value, or an empty string if absent."""
    lines = note_path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        return ""

    for line in lines[1:]:
        if line.strip() in {"---", "..."}:
            break

        match = re.match(r"^course\s*:\s*(.*?)\s*$", line)
        if not match:
            continue

        value = match.group(1)
        if len(value) >= 2 and value[0] == value[-1] == "'":
            return value[1:-1].replace("''", "'")
        if len(value) >= 2 and value[0] == value[-1] == '"':
            return json.loads(value)
        return value

    return ""


def relative_path(project_root: Path, note_path: Path) -> str:
    return note_path.relative_to(project_root).as_posix()


def personal_note_paths(project_root: Path) -> list[Path]:
    notes_directory = project_root / "notes" / "personal"
    if not notes_directory.is_dir():
        raise FileNotFoundError(
            f"personal notes directory not found: {notes_directory}"
        )

    return sorted(
        (
            path
            for path in notes_directory.rglob("*.md")
            if path.is_file()
        ),
        key=lambda path: relative_path(project_root, path),
    )


def ordered_note_paths(project_root: Path) -> list[Path]:
    theorem_path = project_root / THEOREMS_NOTE
    if not theorem_path.is_file():
        raise FileNotFoundError(f"theorem index not found: {theorem_path}")

    khan_note_paths = [project_root / note_path for note_path in KHAN_ACADEMY_NOTES]
    missing_khan_notes = [path for path in khan_note_paths if not path.is_file()]
    if missing_khan_notes:
        missing = ", ".join(str(path) for path in missing_khan_notes)
        raise FileNotFoundError(f"Khan Academy note not found: {missing}")

    remaining_personal_notes = [
        path for path in personal_note_paths(project_root) if path != theorem_path
    ]
    return [theorem_path, *khan_note_paths, *remaining_personal_notes]


def render_book_profile(project_root: Path, note_paths: list[Path]) -> str:
    chapters = [
        relative_path(project_root, path)
        for path in note_paths
    ]
    courses = [
        front_matter_course(path)
        for path in note_paths
    ]

    lines = [
        "# Generated by scripts/generate-book-profile.py; do not edit.",
        "book:",
        "  chapters:",
        f"    - {json.dumps('index.md')}",
    ]
    lines.extend(f"    - {json.dumps(chapter)}" for chapter in chapters)
    lines.extend(
        [
            "metadata:",
            "  academy-chapter-courses:",
            f"    {json.dumps('1')}: {json.dumps('')}",
        ]
    )
    lines.extend(
        f"    {json.dumps(str(index))}: {json.dumps(course)}"
        for index, course in enumerate(courses, start=2)
    )
    return "\n".join(lines) + "\n"


def render_site_profile(project_root: Path, note_paths: list[Path]) -> str:
    theorem_path, *remaining_note_paths = note_paths
    khan_note_paths = remaining_note_paths[: len(KHAN_ACADEMY_NOTES)]
    personal_notes = remaining_note_paths[len(KHAN_ACADEMY_NOTES) :]

    lines = [
        "# Generated by scripts/generate-book-profile.py; do not edit.",
        "website:",
        "  sidebar:",
        "    contents:",
        f"      - href: {json.dumps('index.md')}",
        "        text: Home",
        f"      - href: {json.dumps(relative_path(project_root, theorem_path))}",
        "        text: Theorems",
        "      - section: Khan Academy — Linear Algebra",
        "        contents:",
    ]
    lines.extend(
        f"          - {json.dumps(relative_path(project_root, path))}"
        for path in khan_note_paths
    )
    lines.extend(
        [
            "      - section: Personal notes",
            "        contents:",
        ]
    )
    lines.extend(
        f"          - {json.dumps(relative_path(project_root, path))}"
        for path in personal_notes
    )
    return "\n".join(lines) + "\n"


def write_if_changed(output_path: Path, content: str) -> None:
    if output_path.is_file() and output_path.read_text(encoding="utf-8") == content:
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        dir=output_path.parent,
        prefix=f".{output_path.name}.",
        delete=False,
    ) as temporary_file:
        temporary_file.write(content)
        temporary_path = Path(temporary_file.name)

    os.replace(temporary_path, output_path)


def main() -> None:
    arguments = parse_arguments()
    project_root = arguments.project_root.resolve()
    output_path = arguments.output
    if not output_path.is_absolute():
        output_path = project_root / output_path
    site_output_path = arguments.site_output
    if not site_output_path.is_absolute():
        site_output_path = project_root / site_output_path

    note_paths = ordered_note_paths(project_root)
    write_if_changed(output_path, render_book_profile(project_root, note_paths))
    write_if_changed(site_output_path, render_site_profile(project_root, note_paths))
    print(
        f"Generated {output_path.name} and {site_output_path.name} "
        f"with {len(note_paths)} note chapters"
    )


if __name__ == "__main__":
    main()
